### PR TITLE
fixes for hap-nodejs v1.0.0

### PR DESCRIPTION
**Pull request by bwp91**
See https://github.com/homebridge/homebridge/blob/beta-1.8.4/CHANGELOG.md#changes-for-developers

### CODE REVIEW

**Comment by bwp91** [comment]
@simont77 @NorthernMan54

**Comment by NebzHB** [comment]
mm sorry, just saw your fix, I have done the push another way.

**Comment by simont77** [comment]
Thanks @NebzHB , let me know when it is ready for publishing to NPM.

**Comment by bwp91** [comment]
i closed this PR because it is no longer needed

**Comment by simont77** [comment]
I know, but need to know from @NebzHB when his (different) fix is ready to publish

**Comment by NebzHB** [comment]
@simont77 yes tested successfully.

**Comment by simont77** [comment]
Done

**Pull request closed without merging**
