### PR TITLE
Converted this.log.debug to debug

### PR DESCRIPTION
**Pull request by NorthernMan54**
Changed this.log.debug to debug, and added the debug module to package.json dependancies.  Also I used the Atom editor and it cleaned up the white space.

### CODE REVIEW

**Comment by simont77** [comment]
Thanks for your PR. I've digged a bit into the debug issue. Could you please explain what is the exact problem with the current revision? Fakegato-history right now uses the logging function provided by homebridge.  In order to show debug messages you should call homebridge with the -D parameter. The homebridge log object is already passed to your plugin by homebridge when the constructor is called. The idea is that your plugin points its local log variable to the one passed by homebridge with a `this.log = log` assignment and then create a new fakegato-history object passing the reference to himself as the second parameter (Accessory). In this way calling `this.log.debug` within fakegato-history causes a debug message to be sent to the central homebridge logging system. Maybe it is not very clean, but I really prefer this logging system to the debug module.  The homebridge logging system prepends to your message date and time and also the name of the plugin generating the message (which is very useful if you have like me multiple plugins using fakegato, debug module will show all messages under a single `fakegato` label). It is also possible to use the logger to issue infos and warnings, and not only debug messages. Any suggestions to continue to use the homebridge logging system in a cleaner way?

**Comment by NorthernMan54** [comment]
I was getting this error when attempting to addEntry, and hence the switch to debug

Code/homebridge-dht/node_modules/fakegato-history/fakegato-history.js:252
            this.log.debug("First entry " + this.accessoryType + ": " + this.firstEntry.toString(16));
                    ^

TypeError: Cannot read property 'debug' of undefined
    at FakeGatoHistoryService.addEntry (/Users/sgracey/Code/homebridge-dht/node_modules/fakegato-history/fakegato-history.js:252:21)
    at Object.<anonymous> (/Users/sgracey/Code/homebridge-dht/index.js:108:45)
    at ChildProcess.exithandler (child_process.js:189:7)
    at emitTwo (events.js:106:13)


Looking deeper, your module is assuming that the accessory has the homebridge logger.

PS On a deeper level, I have been working more closely with HAP-NodeJS, and it uses the debug module and never really used the homebridge logger.

**Comment by simont77** [comment]
Yes, that’s exactly the point and I really prefer the homebridge logger. I saw that in your plugins you got it to work in the present form. If you agree I will close the PR and modidy the readme to clarify that your plugin should pass through the homebrdge logger. In the future I may add an optional parameter to pass your preferred logging system, but right now I would prefer to keep it as is for compatibility and simplicity. That do you think?

**Comment by NorthernMan54** [comment]
Agreed

**Pull request closed without merging**
