### PR TITLE
Added TargetTemperature and ValvePosition to accessoryType 'custom'.

### PR DESCRIPTION
**Pull request by banboobee**
Hi simont77
,
Based on the discussions of #97, I Added TargetTemperature and ValvePosition to accessoryType 'custom', and confirmed
that it works well with revised version of 'Homebridge Broadlink RM Pro'. The URL of the proved plug-in is https://github.com/banboobee/homebridge-broadlink-rm.git.

Its my pleasure that if these additions are integrated to your code base.

Thanks in advance.

### CODE REVIEW

**Comment by simont77** [comment]
Thanks for this PR. Could you also update the readme accordingly?

**Comment by banboobee** [comment]
Thank you for prompt reply and sorry for missing the document revision.

I updated the README file.

Please let me know if something are wrong. I'm very new to github and this is my first PR. 

Thanks in advance.

**Comment by simont77** [comment]
Merged and published on npm

**Comment by banboobee** [comment]
I'm glad to hear that. Thank you very much.

**Pull request merged**
